### ISSUE TITLE
exam 1 question

### ISSUE THREAD

**Issue by yangminglintw** [Komegaga/data-engineer-exam#1]
Hi @CheyiLin,

Could I modify the detector.py in exam 1? Thanks.

**Comment by cheyilin** [comment]
@nailo2c FYI.

@Komegaga Thanks for inviting me as contributor in this repo although you don't have to do this, just mention us in issues.

**Comment by aaron-y-chen** [comment]
Hi @Komegaga , you can mention me if you have any questions.

About the detector.py, could I know which part you want to modify?

**Comment by yangminglintw** [comment]
Hi @nailo2c,

I want to add parameters in detect method.

**Comment by aaron-y-chen** [comment]
@Komegaga Got it, please modify it.

**Comment by yangminglintw** [comment]
@nailo2c Thanks for response.

**Comment by aaron-y-chen** [comment]
@Komegaga Please close this issue, thanks.
