### ISSUE TITLE
exam 3 about question 2

### ISSUE THREAD

**Issue by yangminglintw** [Komegaga/data-engineer-exam#2]
Hi @nailo2c,

There is no label information in exam 2 training data. So, I need to label the data in my own way or other suggestion? Thanks.

**Comment by aaron-y-chen** [comment]
Hi @Komegaga , the data of exam 2 has no label.

**Comment by yangminglintw** [comment]
@nailo2c Do you mean I train the LSTM model without label in question 2?

**Comment by aaron-y-chen** [comment]
@Komegaga Yes.

**Comment by yangminglintw** [comment]
@nailo2c Got it! Thanks.

**Comment by aaron-y-chen** [comment]
@Komegaga , please close this issue, thanks!
