### ISSUE TITLE
exam 1: improve the algorithm

### ISSUE THREAD

**Issue by nailo2c** [Komegaga/data-engineer-exam#4]
Hi @Komegaga , nice work on exam 1.

However, if we want our model can find out an anomaly on time, we must change the algorithm from offline learning to online learning.

Please try to make the algorithm can predict every incoming data point, and update the model at the same time. (Hint: use origin *detector.py* and only modify *algorithm.py*)

**Comment by yangminglintw** [comment]
Hi @nailo2c , 

I already modified algorithm.py to real time predict method. Please check the result. Thank you.

**Comment by aaron-y-chen** [comment]
Hi @Komegaga , could you explain why the prediction needs to give a random weight to choice 0 or 1?

```python
pred = random.choices([0, 1], weights=[0.99, 0.01])[0]
```

**Comment by yangminglintw** [comment]
Hi @nailo2c , it's no use code. I will remove it.
