### ISSUE TITLE
exam 1: alarm fatigue

### ISSUE THREAD

**Issue by nailo2c** [Komegaga/data-engineer-exam#5]
Hi @Komegaga , great job for algorithm improvement.

However, our user feedback to us this algorithm is too noisy. Could you design a mechanism to reduce the noise?

**Comment by yangminglintw** [comment]
Hi @nailo2c , I add the if else condition as a mechanism design in the latest update. The average alarm count is lower from 74 to 36. Please check the result, thanks.

**Comment by aaron-y-chen** [comment]
See that, nice work!
